.PHONY: all, clean, rebuild, s21_cat , re, mac_tests, gnu_tests

CC =gcc

FILESDATA_DIR = ../common/filesData
FILE_DIR = ../common/file

INCLUDES =  -I./$(FILESDATA_DIR) -I./$(FILE_DIR) 

CFLAGS =  -Wall -Wextra -Werror -c

LIBFLAGS = -lpcre

SOURCE = s21_grep.c $(wildcard $(FILESDATA_DIR)/*.c) $(wildcard $(FILE_DIR)/*.c)
OBJECTS = $(SOURCE:.c=.o)



EXECUTABLE = s21_grep

.PHONY: s21_grep
s21_grep: all

.PHONY: all

all: $(OBJECTS)
	$(CC) $(INCLUDES) $(OBJECTS) -o $(EXECUTABLE) $(LIBFLAGS) 


.PHONY: re
re: rebuild

.PHONY: rebuild
rebuild: clean all

.PHONY: mac_tests
mac_tests:
	./test_func_grep.sh
	./test_leak_grep_mac.sh

.PHONY: gnu_tests
gnu_tests:
	./test_func_grep.sh
	./test_leak_grep_gnu.sh



%.o: %.c
	$(CC)  $(INCLUDES) $(CFLAGS) $< -o $@ $(LIBFLAGS)

.PHONY: clean
clean:
	-rm $(EXECUTABLE)
	-rm $(OBJECTS)